---
# This is a sample database file for the ActiveRecord ORM
:development: &defaults
  :adapter: mysql
  :database: rickrolldb_prod
  :username: eyebeam
  :password: eyebeam3
  :host: localhost

:test:
  <<: *defaults
  :database: rickrolldb_test

:production:
  <<: *defaults
  :username: eyebeam
  :password: eyebeam3
  :database: rickrolldb_prod
